
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 10 19:46:24 GMT-05:00 2025
//----------------------------------------------------

package analizador2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 35;
  public static final int In = 8;
  public static final int True = 25;
  public static final int NumeroEntero = 37;
  public static final int PuntoComa = 23;
  public static final int Coma = 22;
  public static final int Llave_c = 21;
  public static final int Def = 9;
  public static final int Llave_a = 20;
  public static final int If = 2;
  public static final int Op_asignacion = 36;
  public static final int From = 10;
  public static final int Potencia = 33;
  public static final int None = 27;
  public static final int Else = 4;
  public static final int Break = 48;
  public static final int Error = 49;
  public static final int Corchete_c = 15;
  public static final int Corchete_a = 13;
  public static final int Punto = 12;
  public static final int Return = 16;
  public static final int While = 5;
  public static final int Int = 39;
  public static final int NumeroDecimal = 38;
  public static final int Division = 31;
  public static final int Cadena = 45;
  public static final int Float = 40;
  public static final int Parentesis_c = 19;
  public static final int Modulo = 32;
  public static final int Parentesis_a = 18;
  public static final int For = 7;
  public static final int Elif = 3;
  public static final int EOF = 0;
  public static final int DosPuntos = 24;
  public static final int error = 1;
  public static final int Import = 11;
  public static final int False = 26;
  public static final int Flecha = 14;
  public static final int Char = 46;
  public static final int Print = 17;
  public static final int Op_logico = 34;
  public static final int Const = 41;
  public static final int String = 43;
  public static final int Identificador = 47;
  public static final int Input = 6;
  public static final int Resta = 29;
  public static final int Bool = 42;
  public static final int Multiplicacion = 30;
  public static final int Suma = 28;
  public static final int Main = 44;
}

